name: Build and Deploy

on:
  push:
    branches:
      - main  # або будь-яка інша гілка, яку ти використовуєш

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # або 'zulu' чи інша доступна дистрибуція JDK

    - name: Create Firebase Service Account Key
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > src/main/resources/firebase_service_account_key.json

    - name: Extract Version from pom.xml
      id: extract-version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Make script executable
      run: chmod +x ./get-jar-name.sh

    - name: Get JAR Name
      id: get-jar-name
      run: |
        JAR_NAME=$(./get-jar-name.sh)
        echo "JAR_NAME=$JAR_NAME" >> $GITHUB_ENV

    - name: Stop Render Database
      run: |
        curl -X PATCH https://api.render.com/v1/services/${{ secrets.RENDER_API_KEY }}/stop \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

    - name: Start Render Database
      run: |
          curl -X PATCH https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/start \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

    - name: Build Project
      run: |
        mvn clean package -Dspring.profiles.active=server
          
    - name: Deploy to Render
      env:
        # згенерований ключ на Render
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        # Render hostname
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        # шлях до БД
        RENDER_DATABASE_URL: ${{ secrets.RENDER_DATABASE_URL }}  # Додайте URL бази даних
        # імʼя користувача
        RENDER_DB_USER_NAME: ${{ secrets.RENDER_DB_USER_NAME }}
        # пароль з лінки Render для запуску БД
        RENDER_PGPASSWORD: ${{ secrets.RENDER_PGPASSWORD }}
        # імʼя БД
        RENDER_DATABASE_SERVICE_ID: ${{ secrets.RENDER_DATABASE_SERVICE_ID }}
      run: |
        # Наприклад, ви можете перевірити стан бази даних
        # curl -X POST "https://api.render.com/v1/services/$RENDER_DATABASE_SERVICE_ID/restart" \
        #   -H "Authorization: Bearer $RENDER_API_KEY" \
        #   -H "Content-Type: application/json"

        JAR_NAME=$(echo $JAR_NAME)
        VERSION=$(echo $VERSION)
        curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main", "version": "'"$VERSION"'", "jar_name": "'"$JAR_NAME"'"}'
